transitweb/urls.py
from django.conf.urls import *
from transitweb import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^notifications/mark/$', views.mark_as_read, name="mark_as_read"),
    url(r'^notifications/remove/$', views.remove_notification, name="remove_notification"),

    url(r'^management/add_equipment/$', views.add_equipment, name="add_equipment"),
    url(r'^management/add_occult/$', views.add_occult, name="add_occult"),
    url(r'^notifications/$', views.see_notifications, name="see_notifications"),
    url(r'^occultation/(?P<occult_id>[\w\-]+)/subscribe/$', views.subscribe_occult, name="subscribe"),
    url(r'^occultation/send/(?P<occult_id>[\w\-]+)/(?P<equipment_id>[\w\-]+)$', views.add_result, name="add_result"),
    url(r'^occultation/(?P<occult_id>[\w\-]+)/$', views.occult_page, name="occultation"),

    url(r'^result/(?P<result_id>[\w\-]+)/$', views.see_result, name='see_result'),

    url(r'^workspace/observer/$', views.workspace_observer, name='workspace_observer'),
    url(r'^workspace/astronomer/$', views.workspace_astronomer, name='workspace_astronomer'),

    url(r'^accounts/profile/$', views.user_profile, name='user_profile'),
    url(r'^accounts/login/$', views.user_login, name='login'),
    url(r'^accounts/logout/$', views.user_logout, name='logout'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/update_profile/$', views.edit_profile, name='update_profile'),
    url(r'^accounts/edit_equipment/(?P<equipment_id>[\w\-]+)/$', views.edit_equipment, name='edit_equipment'),
    url(r'^accounts/delete_equipment/(?P<equipment_id>[\w\-]+)/$', views.delete_equipment, name='delete_equipment'),

    url(r'^user/(?P<username>[\w\-]+)/$', views.see_profile, name='see_profile')
]

"""
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>\w+)$', views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>\w+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
"""

transitweb_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.conf import settings

"""
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/'
"""
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'transitweb_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('transitweb.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    #url(r'^accounts/', include('registration.backends.simple.urls')),
)

transitweb/models.py
from django.db import models
from datetime import date, time
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver
from tinymce import models as tinymce_models

from django.template.defaultfilters import slugify

class Location(models.Model):
    latitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    longitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    attitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    country = models.CharField(max_length=128)
    additionalInfo = models.CharField(max_length=128)

    def __unicode__(self):
        return unicode(unicode(self.latitude) + "," + unicode(self.longitude))

class Equipment(models.Model):
    mobile = models.BooleanField(default=False)
    country = models.CharField(max_length=128, null=True)
    latitude = models.DecimalField(max_digits=22, decimal_places=18, default=0)
    longitude = models.DecimalField(
            max_digits=22,
            decimal_places=18,
            default=0)
    additionalInfo = models.CharField(max_length=65535, null=True)
    # UserObserver isn't defined yet, "UserObserver" can be used instead
    user = models.ForeignKey("UserObserver", null=True)

    def __unicode__(self):
        return str(self.latitude) + " " + str(self.longitude)

class Profile(models.Model):
    """ en user: username, first_name, last_name, email, password """
    user = models.OneToOneField(User)

    birth_date = models.DateField(default=now, null=True)
    public = models.BooleanField(default=True)
    website = models.URLField(blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    location = models.ForeignKey(Location, null=True)

    def __unicode__(self):
        return str(user.username)

class UserObserver(models.Model):
    user = models.OneToOneField(User)

    def get_UserObserver_with_equipment(find_equipment):
        for u in UserObserver.objects.all():
            if u.equipment == find_equipment:
                return u
        return None

    def __unicode__(self):
        return self.user.username

class UserAstronomer(models.Model):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

class Occultation(models.Model):
    datePrediction = models.DateField(default=now)
    timePrediction = models.TimeField(default=now)
    additionalInfo = models.CharField(max_length=128, null=True)
    usersGo = models.ManyToManyField(UserObserver, null=True)
    adenda = tinymce_models.HTMLField(null=True)
    reporter = models.ForeignKey(UserAstronomer, null=True)

    attachedFile = models.FileField(null = True)
    attachedImage = models.ImageField(null = True)

    def __unicode__(self):
        return unicode("Occultation " + unicode(self.additionalInfo))

class Subscription(models.Model):
    occultation = models.ForeignKey(Occultation)
    equipment = models.ForeignKey(Equipment)

    additionalInfo = models.CharField(max_length=4096, null=True)

    def __unicode__(self):
        return "no str info"
        return "Occultation: " + str(occultation) + ", user: " + str(equipment)

class Result(models.Model):
    equipment = models.ForeignKey(Equipment)
    occultation = models.ForeignKey(Occultation)

    report = models.CharField(max_length=65535)
    adenda = tinymce_models.HTMLField(null=True)

    def __unicode__(self):
        return str("Result ID: " + str(self.id))

class NotificationManager(models.Manager):
    NEW_OCCULT_MESSAGE = {
        "subject": "New occultation added",
        "message": "A new occultation has been added to the system. <br><br>Please, have a look at it and do not hesitate to ask any question to the reporter. <br><br>Regards."
    }

    NEW_RESULT_MESSAGE = {
        "subject": "New result of an occultation added",
        "message": "An user has uploaded a new result to the system. <br><br>Please, consider having a look at it, just for check the format. <br><br>Regards."
    }

    def send_notification_to_observers(
            self,
            message = NEW_OCCULT_MESSAGE,
            link = None):
        for user in UserObserver.objects.all():
            body = str(message.get("message"))
            if link is not None:
                body += "<br><br>Related link: <a href=\""
                body += str(link)
                body += "\">"
                body += str(link) + "</a>"
            self.create(
                    receiver = user.user,
                    subject = message.get("subject"),
                    message = body,
                    read = False)

    def send_notification_to_astronomers(self):
        pass

    def send_notification_to_everyone(self):
        pass

    def send_notification_to_someone(self, user):
        pass

class Notification(models.Model):
    receiver = models.ForeignKey(User)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=65535, null=True)
    read = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now=True)

    objects = NotificationManager()

    def __unicode__(self):
        return str(str(self.receiver) + ": " + str(self.subject))

transitweb/forms.py
from django import forms
from transitweb.models import *
from django.utils.timezone import now
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE

class OccultationForm(forms.ModelForm):
    datePrediction = forms.DateField(help_text="Date of prediction",
                                     input_formats=('%d/%m/%Y','%d-%m-%Y'))
    timePrediction = forms.TimeField(help_text="Time of prediction")
    #location = forms.ForeignKey(Location)
    additionalInfo = forms.CharField(max_length=128, help_text="Extra info", required=False)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    #usersGo = forms.ManyToManyField(UserObserver)
    #location = forms.ForeignKey(Location)
    adenda = forms.CharField(widget=TinyMCE(attrs={'cols':80, 'rows':30}))
    attachedImage = forms.FileField(required = False)
    attachedFile = forms.ImageField(required = False)
    class Meta:
        model = Occultation
        fields = ("datePrediction", "timePrediction", "additionalInfo", "adenda", "attachedImage", "attachedFile")

class EquipmentForm(forms.ModelForm):
    latitude = forms.DecimalField(
            max_digits=22,
            decimal_places=18,
            help_text="Latitude (from the map)",
            widget=forms.NumberInput(attrs={'class': 'form-control'}))
    longitude = forms.DecimalField(
            max_digits=22,
            decimal_places=18,
            help_text="Longitude (from the map)",
            widget=forms.NumberInput(attrs={'class': 'form-control'}))
    country = forms.CharField(
            max_length=128,
            help_text="Country",
            widget=forms.TextInput(attrs={'class': 'form-control'}))
    mobile = forms.BooleanField(
            help_text="Is a mobile equipment? (select for mobile, no select for static)",
            required=False)
    additionalInfo = forms.CharField(
            max_length=128,
            help_text="Additional info",
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Equipment
        fields = ("latitude", "longitude",
                  "country", "mobile", "additionalInfo")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")

class UserProfileForm(forms.ModelForm):
    #website = forms.URLField(label="Website", required=False)
    public = forms.BooleanField(label="Public profile account?", required=False)

    class Meta:
        model = Profile
        fields = ("birth_date", "country", "website", "phone", "public")

class EditProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    birth_date = forms.DateField(required=False)
    country = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    public = forms.BooleanField(required=False)

    class Meta:
        model = Profile
        fields = ("website", "birth_date", "country", "phone", "public")

class EditEquipmentForm(forms.ModelForm):
    mobile = forms.BooleanField(required=False)
    country = forms.CharField(required=False)
    latitude = forms.DecimalField(required=False)
    longitude = forms.DecimalField(required=False)
    additionalInfo = forms.CharField(required=False)

    class Meta:
        model = Equipment
        fields = ("mobile", "country", "latitude", "longitude", "additionalInfo")

class AddResultForm(forms.ModelForm):
    report = forms.CharField(help_text="Data report", widget=forms.Textarea(attrs={'cols': 40, 'rows': 20}))
    adenda = forms.CharField(help_text="Other related information", required=False, widget=TinyMCE(attrs={'cols':40, 'rows':20}))
    #telescope = forms.ChoiceField(choices=((1, "opcion 1"), (2, "opcion 2")))

    class Meta:
        model = Result
        fields = ("report", "adenda")

"""
class ChangeAccount(forms.ModelForm):
    username = forms.CharField(default)
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")
"""

transitweb/templates/accounts/base_profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile account{% endblock %}

{% block body_block %}

<div class="page-header">
<h1> Profile account: {{ user.username }} </h1>
</div>

 <div class="col-md-12">
   <div class="panel panel-info">
    <div class="panel-heading">
     <h3 class="panel-title">Profile</h3>
    </div>
    <div class="panel-body">
     <div class="panel panel-info">
      <div class="panel-heading">
       <h3 class="panel-title">User account settings</h3>
      </div>
      <div class="panel-body">
<p>Username: {{ user.username }}</p>
<p>E-mail: {% if user.email %} {{user.email}} {% else %} No e-mail added yet {% endif %}</p>
<p>Date joined: {{user.date_joined}}</p>
      </div>
     </div>
     <div class="panel panel-info">
      <div class="panel-heading">
       <h3 class="panel-title">Personal information</h3>
      </div>
      <div class="panel-body">
<p>First name: {% if user.first_name %} {{user.first_name}} {% else %} - {% endif %}</p>
<p>Last name: {% if user.last_name %} {{user.last_name}} {% else %} - {% endif %}</p>
<p>Website: {{ user.profile.website }}</p>
<p>Birth date: {{ user.profile.birth_date }} </p>
<p>Country: {{ user.profile.country }} </p>
<p>Phone: {{ user.profile.phone }} </p>
<p>Location: {{ user.profile.location }} </p>
<p>Allow non-users get to the profile: {% if user.profile.public != True %} No {% else %} Yes {% endif %} </p>
<p><a href="{% url 'update_profile' %}" class="btn btn-default">Change personal data</a></p>
      </div>
     </div>

    </div>
   </div>

{% block profile_panel_telescope %}{% endblock %}

{% block profile_panel_occults %}{% endblock %}

 </div>

<p>{{ user_profile_data.website }}</p>

{% endblock %}

transitweb/templates/accounts/edit_equipment.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Edit equipment{% endblock %}
{% block heading %}Edit equipment{% endblock %}

{% block body_block %}

<form method="POST" action="{% url 'edit_equipment' equipment_id=equipment_id %}" class="" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

{% endblock %}

transitweb/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Edit profile{% endblock %}
{% block heading %}Edit profile{% endblock %}

{% block body_block %}

<form method="POST" action="{% url 'update_profile' %}" class="" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

{% endblock %}

transitweb/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock %}
{% block heading %}Log in{% endblock %}

{% block body_block %}

 <form id="login_form" method="post" action="/accounts/login/">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />

    <input type="submit" value="Log in" />
  </form>

  <p>Not a member? <a href="{% url 'register' %}">Register</a>!</p>

{% endblock %}

transitweb/templates/accounts/logout.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}
{% block heading %}Logged out{% endblock %}

{% block body_block %}

 <p>You are now logged out</p>

{% endblock %}

transitweb/templates/accounts/profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Profile account{% endblock %}
{% block heading %}Profile{% endblock %}

{% block body_block %}

<div class="page-header">
<h1> Profile account: {{ user.username }} </h1>
</div>

 <div class="col-md-12">
   <div class="panel panel-info">
    <div class="panel-heading">
     <h3 class="panel-title">Profile</h3>
    </div>
    <div class="panel-body">
     <div class="panel panel-info">
      <div class="panel-heading">
       <h3 class="panel-title">User account settings</h3>
      </div>
      <div class="panel-body">
<p>Username: {{ user.username }}</p>
<p>E-mail: {% if user.email %} {{user.email}} {% else %} No e-mail added yet {% endif %}</p>
<p>Date joined: {{user.date_joined}}</p>
      </div>
     </div>
     <div class="panel panel-info">
      <div class="panel-heading">
       <h3 class="panel-title">Personal information</h3>
      </div>
      <div class="panel-body">
<p>First name: {% if user.first_name %} {{user.first_name}} {% else %} - {% endif %}</p>
<p>Last name: {% if user.last_name %} {{user.last_name}} {% else %} - {% endif %}</p>
<p>Website: {{ user.profile.website }}</p>
<p>Birth date: {{ user.profile.birth_date }} </p>
<p>Country: {{ user.profile.country }} </p>
<p>Phone: {{ user.profile.phone }} </p>
<p>Location: {{ user.profile.location }} </p>
<p>Allow non-users get to the profile: {% if user.profile.public != True %} No {% else %} Yes {% endif %} </p>
<p><a href="{% url 'update_profile' %}" class="btn btn-default">Change personal data</a></p>
      </div>
     </div>

    </div>
   </div>

 </div>

{% endblock %}

transitweb/templates/accounts/profile_astronomer.html
{% extends 'accounts/base_profile.html' %}

{% load staticfiles %}

{% block profile_panel_occults %}
<div class="panel panel-info">

 <div class="panel-heading">
  <h3 class="panel-title">Occultations added</h3>
 </div>

<div class="panel-body">
<p>Plenty of occults thank you</p>
</div>
<div class="panel-footer">
<p><a href="{% url 'add_occult' %}">Add more occults</a>
</div>

</div>
{% endblock %}

transitweb/templates/accounts/profile_observer.html
{% extends 'accounts/base_profile.html' %}

{% load staticfiles %}

{% block profile_panel_equipment %}

  <div class="panel panel-info">
   <div class="panel-heading">
    <h3 class="panel-title">Equipments</h3>
   </div>
   <div class="panel-body">

     {% if userObserver.equipment_set %}
     {% for equipment in userObserver.equipment_set.all %}
     <div class="panel panel-info">
      <div class="panel-body">
       <p>Mobile equipment: {{ equipment.mobile }}</p>
       <p>Country: {{ equipment.country }}</p>
       <p>Latitude of equipment: {{ equipment.latitude }}  </p>
       <p>Longitude of equipment: {{ equipment.longitude }} </p>
       <p>Extra info: {{ equipment.additionalInfo }}</p>
      </div>
      <div class="panel-footer">
       <a href="{% url 'edit_equipment' equipment_id=equipment.id %}" class="btn btn-default">Edit equipment configuration</a>
       <a href="{% url 'delete_equipment' equipment_id=equipment.id %}" class="btn btn-default">Remove equipment</a>
      </div>
     </div>
     {% endfor %}
     {% endif %}
    </div>
    <div class="panel-footer">
      <a href="{% url 'add_equipment' %}" class="btn btn-default">Add new equipment</a>
    </div>
   </div>
{% endblock %}

transitweb/templates/accounts/register.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Register{% endblock %}
{% block heading %}Register{% endblock %}

{% block body_block %}

{% if registered %}
Registered!
{% else %}

<form id="user_form" method="post" class="form-horizontal" action="/accounts/register/">

{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}

<input type="submit" name="submit" value="Register" />

</form>

{% endif %}
{% endblock %}

transitweb/templates/accounts/registration_complete.html
{% extends "base.html" %}

{% block title %}Registration complete{% endblock %}

{% block body_block %}
<h1>Registration complete</h1>
 <p>You are now registered</p>
{% endblock %}

transitweb/templates/accounts/registration_form.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}
{% block heading %}Register{% endblock %}

{% block body_block %}

 <form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" />
  </form>

{% endblock %}