transitweb/urls.py
from django.conf.urls import *
from transitweb import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^notifications/mark/$', views.mark_as_read, name="mark_as_read"),
    url(r'^notifications/remove/$', views.remove_notification, name="remove_notification"),

    url(r'^management/add_equipment/$', views.add_equipment, name="add_equipment"),
    url(r'^management/add_occult/$', views.add_occult, name="add_occult"),
    url(r'^notifications/$', views.see_notifications, name="see_notifications"),
    url(r'^occultation/(?P<occult_id>[\w\-]+)/subscribe/$', views.subscribe_occult, name="subscribe"),
    url(r'^occultation/send/(?P<occult_id>[\w\-]+)/(?P<equipment_id>[\w\-]+)$', views.add_result, name="add_result"),
    url(r'^occultation/(?P<occult_id>[\w\-]+)/$', views.occult_page, name="occultation"),

    url(r'^result/(?P<result_id>[\w\-]+)/$', views.see_result, name='see_result'),

    url(r'^workspace/observer/$', views.workspace_observer, name='workspace_observer'),
    url(r'^workspace/astronomer/$', views.workspace_astronomer, name='workspace_astronomer'),

    url(r'^accounts/profile/$', views.user_profile, name='user_profile'),
    url(r'^accounts/login/$', views.user_login, name='login'),
    url(r'^accounts/logout/$', views.user_logout, name='logout'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/update_profile/$', views.edit_profile, name='update_profile'),
    url(r'^accounts/edit_equipment/(?P<equipment_id>[\w\-]+)/$', views.edit_equipment, name='edit_equipment'),
    url(r'^accounts/delete_equipment/(?P<equipment_id>[\w\-]+)/$', views.delete_equipment, name='delete_equipment'),

    url(r'^user/(?P<username>[\w\-]+)/$', views.see_profile, name='see_profile')
]

"""
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<category_name_slug>\w+)$', views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>\w+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
"""

transitweb_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.conf import settings

"""
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/'
"""
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'transitweb_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('transitweb.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    #url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    #url(r'^accounts/', include('registration.backends.simple.urls')),
)

transitweb/models.py
from django.db import models
from datetime import date, time
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db.models.signals import post_save
from django.dispatch import receiver
from tinymce import models as tinymce_models

from django.template.defaultfilters import slugify

class Location(models.Model):
    latitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    longitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    attitude = models.DecimalField(max_digits=13, decimal_places=10, default=0)
    country = models.CharField(max_length=128)
    additionalInfo = models.CharField(max_length=128)

    def __unicode__(self):
        return unicode(unicode(self.latitude) + "," + unicode(self.longitude))

class Equipment(models.Model):
    mobile = models.BooleanField(default=False)
    country = models.CharField(max_length=128, null=True)
    latitude = models.DecimalField(max_digits=22, decimal_places=18, default=0)
    longitude = models.DecimalField(
            max_digits=22,
            decimal_places=18,
            default=0)
    additionalInfo = models.CharField(max_length=65535, null=True)
    # UserObserver isn't defined yet, "UserObserver" can be used instead
    user = models.ForeignKey("UserObserver", null=True)

    def __unicode__(self):
        return str(self.latitude) + " " + str(self.longitude)

class Profile(models.Model):
    """ en user: username, first_name, last_name, email, password """
    user = models.OneToOneField(User)

    birth_date = models.DateField(default=now, null=True)
    public = models.BooleanField(default=True)
    website = models.URLField(blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    location = models.ForeignKey(Location, null=True)

    def __unicode__(self):
        return str(user.username)

class UserObserver(models.Model):
    user = models.OneToOneField(User)

    def get_UserObserver_with_equipment(find_equipment):
        for u in UserObserver.objects.all():
            if u.equipment == find_equipment:
                return u
        return None

    def __unicode__(self):
        return self.user.username

class UserAstronomer(models.Model):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username

class Occultation(models.Model):
    datePrediction = models.DateField(default=now)
    timePrediction = models.TimeField(default=now)
    additionalInfo = models.CharField(max_length=128, null=True)
    usersGo = models.ManyToManyField(UserObserver, null=True)
    adenda = tinymce_models.HTMLField(null=True)
    reporter = models.ForeignKey(UserAstronomer, null=True)

    attachedFile = models.FileField(null = True)
    attachedImage = models.ImageField(null = True)

    def __unicode__(self):
        return unicode("Occultation " + unicode(self.additionalInfo))

class Subscription(models.Model):
    occultation = models.ForeignKey(Occultation)
    equipment = models.ForeignKey(Equipment)

    additionalInfo = models.CharField(max_length=4096, null=True)

    def __unicode__(self):
        return "no str info"
        return "Occultation: " + str(occultation) + ", user: " + str(equipment)

class Result(models.Model):
    equipment = models.ForeignKey(Equipment)
    occultation = models.ForeignKey(Occultation)

    report = models.CharField(max_length=65535)
    adenda = tinymce_models.HTMLField(null=True)

    def __unicode__(self):
        return str("Result ID: " + str(self.id))

class NotificationManager(models.Manager):
    NEW_OCCULT_MESSAGE = {
        "subject": "New occultation added",
        "message": "A new occultation has been added to the system. <br><br>Please, have a look at it and do not hesitate to ask any question to the reporter. <br><br>Regards."
    }

    NEW_RESULT_MESSAGE = {
        "subject": "New result of an occultation added",
        "message": "An user has uploaded a new result to the system. <br><br>Please, consider having a look at it, just for check the format. <br><br>Regards."
    }

    def send_notification_to_observers(
            self,
            message = NEW_OCCULT_MESSAGE,
            link = None):
        for user in UserObserver.objects.all():
            body = str(message.get("message"))
            if link is not None:
                body += "<br><br>Related link: <a href=\""
                body += str(link)
                body += "\">"
                body += str(link) + "</a>"
            self.create(
                    receiver = user.user,
                    subject = message.get("subject"),
                    message = body,
                    read = False)

    def send_notification_to_astronomers(self):
        pass

    def send_notification_to_everyone(self):
        pass

    def send_notification_to_someone(self, user):
        pass

class Notification(models.Model):
    receiver = models.ForeignKey(User)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=65535, null=True)
    read = models.BooleanField(default=False)
    datetime = models.DateTimeField(auto_now=True)

    objects = NotificationManager()

    def __unicode__(self):
        return str(str(self.receiver) + ": " + str(self.subject))

transitweb/forms.py
from django import forms
from transitweb.models import *
from django.utils.timezone import now
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE

class OccultationForm(forms.ModelForm):
    datePrediction = forms.DateField(help_text="Date of prediction",
                                     input_formats=('%d/%m/%Y','%d-%m-%Y'))
    timePrediction = forms.TimeField(help_text="Time of prediction")
    #location = forms.ForeignKey(Location)
    additionalInfo = forms.CharField(max_length=128, help_text="Extra info", required=False)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    #usersGo = forms.ManyToManyField(UserObserver)
    #location = forms.ForeignKey(Location)
    adenda = forms.CharField(widget=TinyMCE(attrs={'cols':80, 'rows':30}))
    attachedImage = forms.FileField(required = False)
    attachedFile = forms.ImageField(required = False)
    class Meta:
        model = Occultation
        fields = ("datePrediction", "timePrediction", "additionalInfo", "adenda", "attachedImage", "attachedFile")

class EquipmentForm(forms.ModelForm):
    latitude = forms.DecimalField(
            max_digits=22,
            decimal_places=18,
            help_text="Latitude (from the map)",
            widget=forms.NumberInput(attrs={'class': 'form-control'}))
    longitude = forms.DecimalField(
            max_digits=22,
            decimal_places=18,
            help_text="Longitude (from the map)",
            widget=forms.NumberInput(attrs={'class': 'form-control'}))
    country = forms.CharField(
            max_length=128,
            help_text="Country",
            widget=forms.TextInput(attrs={'class': 'form-control'}))
    mobile = forms.BooleanField(
            help_text="Is a mobile equipment? (select for mobile, no select for static)",
            required=False)
    additionalInfo = forms.CharField(
            max_length=128,
            help_text="Additional info",
            required=False,
            widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Equipment
        fields = ("latitude", "longitude",
                  "country", "mobile", "additionalInfo")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")

class UserProfileForm(forms.ModelForm):
    #website = forms.URLField(label="Website", required=False)
    public = forms.BooleanField(label="Public profile account?", required=False)

    class Meta:
        model = Profile
        fields = ("birth_date", "country", "website", "phone", "public")

class EditProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    birth_date = forms.DateField(required=False)
    country = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    public = forms.BooleanField(required=False)

    class Meta:
        model = Profile
        fields = ("website", "birth_date", "country", "phone", "public")

class EditEquipmentForm(forms.ModelForm):
    mobile = forms.BooleanField(required=False)
    country = forms.CharField(required=False)
    latitude = forms.DecimalField(required=False)
    longitude = forms.DecimalField(required=False)
    additionalInfo = forms.CharField(required=False)

    class Meta:
        model = Equipment
        fields = ("mobile", "country", "latitude", "longitude", "additionalInfo")

class AddResultForm(forms.ModelForm):
    report = forms.CharField(help_text="Data report", widget=forms.Textarea(attrs={'cols': 40, 'rows': 20}))
    adenda = forms.CharField(help_text="Other related information", required=False, widget=TinyMCE(attrs={'cols':40, 'rows':20}))
    #telescope = forms.ChoiceField(choices=((1, "opcion 1"), (2, "opcion 2")))

    class Meta:
        model = Result
        fields = ("report", "adenda")

"""
class ChangeAccount(forms.ModelForm):
    username = forms.CharField(default)
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")
"""

transitweb/templates/management/add_equipment.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add equipment{% endblock %}
{% block heading %}Add new equipment{% endblock %}

{% block body_block %}

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Map</h3>
  </div>
  <div class="panel-body">
    <p>Select in the map the current location of your equipment. Be as accurate as possible.</p>
    <div id="map">Map will be loaded here</div>
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Information</h3>
  </div>
  <div class="panel-body">
    <form id="equipment_form" method="post"  action="/management/add_equipment/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        <div class="form-group">
          {{ field.errors }}
          <label for="{{ field.id_for_label }}">{{ field.help_text }}</label>
          {{ field }}
        </div>
      {% endfor %}
      <input type="submit" name="submit" value="Create equipment" />
    </form>
  </div>
</div>

<script>
var preMarker;
function initMap() {
  var myLatlng = {
    lat: 0,
    lng: 0
  };

  var map = new google.maps.Map(
    document.getElementById("map"),
    {
      zoom: 4,
      center: myLatlng
    }
  );

  map.addListener('click', function(e){
    placeMarkerAndPanTo(e.latLng, map);
  });
}

function placeMarkerAndPanTo(latlng, map){
  var marker = new google.maps.Marker({
    position: latlng,
    map: map
  });
  if (preMarker != undefined){
    preMarker.setMap(null);
  }
  preMarker = marker;
  document.getElementById("id_latitude").value = latlng.lat();
  document.getElementById("id_longitude").value = latlng.lng();
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBn9s1CrT7tMwGFpXXOMz1YJiefh8LYFCU&callback=initMap" async defer></script>
{% endblock %}

{% block masscripts %}
<style>
#map {
  height: 400px;
}
</style>

{% endblock %}

transitweb/templates/management/add_occult.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add occultation{% endblock %}
{% block heading %}Add occultation{% endblock %}

{% block head_tag %}
{{ form.media }}
{% endblock %}

{% block body_block %}

<form id="occult_form" method="post" class="form-horizontal" action="/management/add_occult/" enctype="multipart/form-data">

  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{ hidden }}
  {% endfor %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.errors }}
      <label class="control-label">{{ field.help_text }}</label>
      {{ field }}
    </div>
  {% endfor %}

  <input type="submit" name="submit" value="Create occultation" />
</form>

{% endblock %}


{% block masscripts %}
<script>

$(document).ready(function(){
  $("#id_datePrediction").datepicker({dateFormat: 'dd/mm/yy'});
});

</script>
{% endblock %}

transitweb/templates/management/add_result.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add result{% endblock %}
{% block heading %}Add result{% endblock %}

{% block head_tag %}
{{ form.media }}
{% endblock %}

{% block body_block %}

<form id="occult_form" method="post" class="form-horizontal" action="/occultation/send/{{ occult_id }}/{{ equipment_id }}">

{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}

{% for field in form.visible_fields %}
<div class="form-group">
{{ field.errors }}
<label class="control-label">{{ field.help_text }}</label>
{{ field }}
</div>
{% endfor %}

<input type="submit" name="submit" value="Send report" />

</form>

{% endblock %}

transitweb/templates/management/notifications.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Notifications{% endblock %}
{% block heading %}Notifications{% endblock %}

{% block body_block %}

<div class="row">
  <div class="col-md-12">
    {% if notifications_unread %}
      <h2>Unread notifications</h2>
      <ul class="list-group">
        {% for notif in notifications_unread %}
          <li class="list-group-item" id="unread{{ forloop.counter }}" class="unread_elements">
            <h4 class="list-group-item-heading">{{ notif.subject }}</h4>
            <p class="list-group-item-text">{{ notif.message|safe }}</p>
            <hr>
            <a class="btn btn-default marker" href="#" role="button" data-notifid="{{ notif.id }}">Mark as read</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}
    <hr>
    {% if notifications %}
      <ul class="list-group">
        {% for notif in notifications%}
          <li class="list-group-item">
            <h4 class="list-group-item-heading">
              <a href="#item{{ forloop.counter}}" data-toggle="collapse" aria-expanded="false" aria-controls="item{{ forloop.counter}}">
                {{ notif.subject }} <i>( {{ notif.datetime|date:"d/m/y H:i" }} )</i>
              </a>
            </h4>
            <div class="collapse" id="item{{ forloop.counter }}">
              <p class="list-group-item-text">{{ notif.message|safe }}</p>
              <hr>
              <a class="btn btn-default deleter" href="#" role="button" data-notifid="{{ notif.id }}">Delete</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      No notifications
    {% endif %}

  </div>
</div>

{% endblock %}

{% block masscripts %}
<script>

$(document).ready(function(){
  $(".marker").click(function(){
    $(this).parent().fadeTo(200, 0).slideUp(200);
    var notif_id;
    notif_id = $(this).attr("data-notifid");
    $.get("{% url 'mark_as_read' %}", {notif_id: notif_id});
  });
  $(".deleter").click(function(){
    $(this).parent().parent().fadeTo(200, 0).slideUp(200);
    var notif_id;
    notif_id = $(this).attr("data-notifid");
    $.get("{% url 'remove_notification' %}", {notif_id: notif_id});
  });
});

</script>
{% endblock %}